import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Sidebar from '@/components/Sidebar'

import { KumaRegistry } from "@kuma-ui/next-plugin/registry"

import { SessionProvider } from 'next-auth/react';
import Window from '@/components/Window'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Twitter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode,
  modal: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <KumaRegistry>
          <Window>
            {children}
          </Window>
          {modal}
        </KumaRegistry>
      </body>
    </html>
  )
}
