import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './global.css'

import Header from '@/components/Header'
import Footer from '@/components/Footer'

import { SessionProvider } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Twitter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode,
  modal: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        {modal}
        <Footer />
      </body>
    </html>
  )
}
