version: "3.8"

services:
  backend:
    container_name: backend
    hostname: backend
    build:
      context: ./backend
      dockerfile: ./.docker/Dockerfile.Dev
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8888:8888
    depends_on:
      database:
        condition: service_healthy
    networks:
      - twitter
    volumes:
      - ./backend:/app
    profiles: ["dev"]

  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: ./frontend-test
      dockerfile: ./.docker/Dockerfile.Dev
    environment:
      TZ: Asia/Tokyo
    ports:
      - 3000:3000
    networks:
      - twitter
    volumes:
      - ./frontend-test:/app
      - /app/node_modules
    profiles: ["dev"]

  database:
    container_name: database
    build: database/
    hostname: database
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: twitter
      MYSQL_PASSWORD: twitter
      MYSQL_ROOT_PASSWORD: twitter
      MYSQL_DATABASE: twitter
      TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql-files
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - twitter
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $MYSQL_USER -p $MYSQL_PASSWORD

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - twitter

  backend-prd:
    build:
      context: ./backend
      dockerfile: ./.docker/Dockerfile
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8888:8888
    depends_on:
      - database
    networks:
      - twitter
    profiles: ["prd"]

  frontend-prd:
    build:
      context: ./frontend
      dockerfile: ./.docker/Dockerfile
    environment:
      TZ: Asia/Tokyo
    ports:
      - 3000:3000 
    networks:
      - twitter
    profiles: ["prd"]


volumes:
  mysql-data:

networks:
  twitter:

