
version: "3.8"

services:
  backend:
    container_name: backend
    hostname: backend
    build:
      context: ./backend
      dockerfile: ./.docker/Dockerfile.Dev
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8888:8888
    depends_on:
      - db
    networks:
      - twitter
    volumes:
      - ./backend:/app
    profiles: ["dev"]

  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: ./.docker/Dockerfile.Dev
    environment:
      TZ: Asia/Tokyo
    ports:
      - 3000:3000
    networks:
      - twitter
    volumes:
      - ./frontend:/app
    profiles: ["dev"]

  db:
    container_name: db
    build: db/
    hostname: db
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: twitter
      MYSQL_PASSWORD: twitter
      MYSQL_ROOT_PASSWORD: twitter
      MYSQL_DATABASE: twitter
      TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql-files
      - ./db/initdb.d:/docker-entrypoint-initdb.d

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  backend-prd:
    build:
      context: ./backend
      dockerfile: ./.docker/Dockerfile
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8888:8888
    depends_on:
      - db
    networks:
      - twitter
    profiles: ["prd"]

  frontend-prd:
    build:
      context: ./frontend
      dockerfile: ./.docker/Dockerfile
    environment:
      TZ: Asia/Tokyo
    ports:
      - 3000:3000 
    networks:
      - twitter
    profiles: ["prd"]


volumes:
  mysql-data:

networks:
  twitter:

