import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Window from '@/components/Window'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Twitter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode,
  modal: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Window>
          {children}
        </Window>
        {modal}
      </body>
    </html>
  )
}
