FROM node:18-alpine

WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

COPY ./package.json ./
COPY ./panda.config.ts ./
RUN npm install -g pnpm && pnpm install

EXPOSE 3000

CMD [ "pnpm", "dev" ]

